const sessionKey="lunch-poc-card-session-v8",logKey="lunch-poc-kiosk-order-log-v8",languageKey="lunch-poc-kiosk-language-v10";
let employee;try{employee=JSON.parse(sessionStorage.getItem(sessionKey))}catch{}if(!employee)location.replace('index.html');
let language=localStorage.getItem(languageKey)||'en',mode='own',own={},guest={},expandedDays=new Set(),timeoutSeconds=60,timeoutTimer;
const text={
 en:{myLunch:'My lunch',guestLunches:'Guest lunches',orderOwn:'Order your own lunch',orderHint:'Select meals below, then save. The screen returns to card login automatically.',workTask:'Work task / project',workHelp:'Required for guest lunches. Comments are stored exactly as entered.',save:'Save and finish',cancel:'Cancel',noLunch:'No lunches selected',selected:n=>`${n} lunch${n===1?'':'es'} selected`,selectMeal:'Select a meal to continue',enterProject:'Enter work task / project for guest lunches',ready:'Ready to save',menu:'Lunch menu',saved:n=>`${n} lunch${n===1?'':'es'} saved. Returning to card login…`,locked:'Ordering closed at 08:30',lockedHelp:'Today’s order is visible but can no longer be changed.'},
 sv:{myLunch:'Min lunch',guestLunches:'Gästluncher',orderOwn:'Beställ din egen lunch',orderHint:'Välj måltider nedan och spara. Skärmen återgår automatiskt till kortinloggningen.',workTask:'Arbetsuppgift / projekt',workHelp:'Obligatoriskt för gästluncher. Kommentaren sparas exakt som den anges.',save:'Spara och avsluta',cancel:'Avbryt',noLunch:'Inga luncher valda',selected:n=>`${n} lunch${n===1?'':'er'} valda`,selectMeal:'Välj en måltid för att fortsätta',enterProject:'Ange arbetsuppgift / projekt för gästluncher',ready:'Klar att spara',menu:'Lunchmeny',saved:n=>`${n} lunch${n===1?'':'er'} sparade. Återgår till kortinloggningen…`,locked:'Beställningen stängde 08:30',lockedHelp:'Dagens beställning visas men kan inte längre ändras.'},
 fi:{myLunch:'Oma lounas',guestLunches:'Vieraslounaat',orderOwn:'Tilaa oma lounaasi',orderHint:'Valitse ateriat alta ja tallenna. Näyttö palaa automaattisesti korttikirjautumiseen.',workTask:'Työtehtävä / projekti',workHelp:'Pakollinen vieraslounaille. Kommentti tallennetaan täsmälleen syötetyssä muodossa.',save:'Tallenna ja lopeta',cancel:'Peruuta',noLunch:'Ei valittuja lounaita',selected:n=>`${n} lounas${n===1?'':'ta'} valittu`,selectMeal:'Valitse ateria jatkaaksesi',enterProject:'Anna vieraslounaan työtehtävä / projekti',ready:'Valmis tallennettavaksi',menu:'Lounaslista',saved:n=>`${n} lounas${n===1?'':'ta'} tallennettu. Palataan korttikirjautumiseen…`,locked:'Tilaus sulkeutui klo 08.30',lockedHelp:'Tämän päivän tilaus näkyy, mutta sitä ei voi enää muuttaa.'}
};
const dayNames={Monday:{sv:'Måndag',fi:'Maanantai'},Tuesday:{sv:'Tisdag',fi:'Tiistai'},Wednesday:{sv:'Onsdag',fi:'Keskiviikko'},Thursday:{sv:'Torsdag',fi:'Torstai'},Friday:{sv:'Fredag',fi:'Perjantai'}};
const categoryNames={main:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},main2:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},vegetarian:{en:'Vegetarian',sv:'Vegetarisk',fi:'Kasvisruoka'},soup:{en:'Soup',sv:'Soppa',fi:'Keitto'},salad:{en:'Salad',sv:'Sallad',fi:'Salaatti'}};
const defaultSalads=[{en:'Vegetarian salad',sv:'Vegetarisk sallad',fi:'Kasvissalaatti',active:true},{en:'Beef salad',sv:'Nötköttssallad',fi:'Naudanlihasalaatti',active:true},{en:'Tuna salad',sv:'Tonfisksallad',fi:'Tonnikalasalaatti',active:true},{en:'Pasta salad with chicken',sv:'Pastasallad med kyckling',fi:'Pastasalaatti kanalla',active:true},{en:'Salmon salad',sv:'Laxsallad',fi:'Lohisalaatti',active:true},{en:'Chicken salad',sv:'Kycklingsallad',fi:'Kanasalaatti',active:true}];
function activeWeek(date){try{const c=JSON.parse(localStorage.getItem('lunch-poc-menu-config-v6'))||JSON.parse(localStorage.getItem('lunch-poc-menu-config-v5'));if(c?.weeks?.length){const day=new Date(date);day.setHours(0,0,0,0);day.setDate(day.getDate()-((day.getDay()+6)%7));const idx=((Math.floor((day-new Date(2026,8,21))/604800000)%c.repeatWeeks)+c.repeatWeeks)%c.repeatWeeks;return c.weeks[idx]}}catch{}return{days:['Monday','Tuesday','Wednesday','Thursday','Friday'].map(day=>({day,meals:[{type:'main',names:{en:'Meatballs with mashed potatoes',sv:'Köttbullar med potatismos',fi:'Lihapullat ja perunamuusi'}},{type:'main2',names:{en:'',sv:'',fi:''}},{type:'vegetarian',names:{en:'Vegetable lasagne',sv:'Grönsakslasagne',fi:'Kasvislasagne'}},{type:'soup',names:{en:'Tomato soup',sv:'Tomatsoppa',fi:'Tomaattikeitto'}}]}))}}
function salads(){try{const saved=JSON.parse(localStorage.getItem('lunch-poc-salads-v5'));return(saved?.length?saved:defaultSalads).filter(s=>s.active!==false)}catch{return defaultSalads}}
function mealName(names){return(names?.[language]||names?.en||'').trim()}function category(type){return categoryNames[type]?.[language]||categoryNames[type]?.en||type}
const simulationLabels={en:'POC: Simulate Friday',sv:'POC: Simulera fredag',fi:'POC: Simuloi perjantai'};function localDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function effectiveToday(){const d=new Date();d.setHours(0,0,0,0);if(document.querySelector('#simulateFriday')?.checked)d.setDate(d.getDate()+((5-d.getDay()+7)%7));return d}function deadlinePassed(){const now=new Date();return now.getHours()>8||(now.getHours()===8&&now.getMinutes()>=30)}function dayLocked(id){return id===localDateKey(effectiveToday())&&deadlinePassed()}function shownDates(){const today=effectiveToday(),weekday=today.getDay();if(weekday===0||weekday===6){const next=new Date(today);next.setDate(today.getDate()+((8-weekday)%7));return Array.from({length:5},(_,i)=>{const d=new Date(next);d.setDate(next.getDate()+i);return d})}const dates=[];const friday=new Date(today);friday.setDate(today.getDate()+(5-weekday));for(let d=new Date(today);d<=friday;d.setDate(d.getDate()+1))dates.push(new Date(d));if(weekday===5){const nextMonday=new Date(today);nextMonday.setDate(today.getDate()+3);for(let i=0;i<5;i++){const d=new Date(nextMonday);d.setDate(nextMonday.getDate()+i);dates.push(d)}}return dates}function buildMenu(){return shownDates().map(dt=>{const week=activeWeek(dt),i=(dt.getDay()+6)%7,d=week.days[i];return{id:localDateKey(dt),day:language==='en'?d.day:(dayNames[d.day]?.[language]||d.day),date:String(dt.getDate()).padStart(2,'0')+'.'+String(dt.getMonth()+1).padStart(2,'0'),meals:[...d.meals.filter(m=>mealName(m.names)).map(m=>({name:mealName(m.names),category:category(m.type)})),...salads().filter(s=>mealName(s)).map(s=>({name:mealName(s),category:category('salad')}))]}})}
let menu=buildMenu();const box=document.querySelector('#kioskWeek'),guestField=document.querySelector('#guestField'),comment=document.querySelector('#guestComment'),languageSelect=document.querySelector('#kioskLanguage');document.querySelector('#employeeName').textContent=employee.employeeName;document.querySelector('#employeeNumber').textContent=`Employee ${employee.employeeNumber}`;languageSelect.value=language;
function key(d,i){return`${d}:${i}`}function orders(){return mode==='own'?own:guest}function total(obj=orders()){return Object.values(obj).reduce((a,b)=>a+Number(b),0)}
function applyText(){const t=text[language];document.querySelector('[data-mode="own"]').textContent=t.myLunch;document.querySelector('[data-mode="guest"]').textContent=t.guestLunches;document.querySelector('#ownNote strong').textContent=t.orderOwn;document.querySelector('#ownNote span').textContent=t.orderHint;document.querySelector('label[for="guestComment"]').childNodes[0].textContent=t.workTask+' ';document.querySelector('#guestField small').textContent=t.workHelp;document.querySelector('#kioskSave').textContent=t.save;document.querySelector('#logoutButton').textContent=t.cancel;document.querySelector('#simulateFridayLabel').textContent=simulationLabels[language]||simulationLabels.en}
function render(){const current=orders();box.innerHTML=menu.map(d=>{const open=expandedDays.has(d.id),locked=dayLocked(d.id);return`<article class="day ${open?'open':''} ${locked?'deadline-locked':''}" data-day="${d.id}"><button class="day-toggle" type="button" aria-expanded="${open}"><span class="chevron"></span><span class="day-name"><strong>${d.day} ${d.date}</strong><span>${locked?text[language].locked:text[language].menu}</span></span><span class="day-total ${d.meals.some((_,i)=>current[key(d.id,i)])?'has-orders':''}">🍴 ${d.meals.reduce((n,_,i)=>n+(current[key(d.id,i)]||0),0)}</span></button><div class="day-content">${locked?`<div class="deadline-lock-note">${text[language].lockedHelp}</div>`:''}${d.meals.map((m,i)=>`<div class="meal-row"><div class="meal-name"><strong>${m.name}</strong><span>${m.category}</span></div><div class="stepper" data-index="${i}"><button class="minus" type="button" ${(locked||!current[key(d.id,i)])?'disabled':''}>−</button><output>${current[key(d.id,i)]||0}</output><button class="plus" type="button" ${locked?'disabled':''}>+</button></div></div>`).join('')}</div></article>`}).join('');update()}
box.addEventListener('click',e=>{resetTimeout();const toggle=e.target.closest('.day-toggle');if(toggle){const id=toggle.closest('.day').dataset.day;expandedDays.has(id)?expandedDays.delete(id):expandedDays.add(id);render();return}const b=e.target.closest('.stepper button');if(!b)return;const day=b.closest('.day').dataset.day;if(dayLocked(day)){const toast=document.querySelector('#toast');toast.textContent=text[language].locked;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800);render();return}const i=+b.closest('.stepper').dataset.index,k=key(day,i),obj=orders();obj[k]=Math.max(0,(obj[k]||0)+(b.classList.contains('plus')?1:-1));if(!obj[k])delete obj[k];expandedDays.add(day);render()});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{resetTimeout();mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));guestField.hidden=mode!=='guest';render()}));comment.addEventListener('input',()=>{resetTimeout();update()});languageSelect.addEventListener('change',()=>{resetTimeout();language=languageSelect.value;localStorage.setItem(languageKey,language);menu=buildMenu();applyText();render()});
document.querySelector('#simulateFriday').addEventListener('change',()=>{resetTimeout();menu=buildMenu();expandedDays.clear();const today=menu.find(d=>d.id===localDateKey(effectiveToday()));if(today)expandedDays.add(today.id);render()});
function update(){const ownCount=total(own),guestCount=total(guest),all=ownCount+guestCount,t=text[language];document.querySelector('#kioskSummary').textContent=all?t.selected(all):t.noLunch;const valid=all>0&&(!guestCount||comment.value.trim());document.querySelector('#kioskStatus').textContent=guestCount&&!comment.value.trim()?t.enterProject:all?t.ready:t.selectMeal;document.querySelector('#kioskSave').disabled=!valid}
function finish(){const locked=localDateKey(effectiveToday());if(dayLocked(locked)){for(const obj of [own,guest])for(const k of Object.keys(obj))if(k.startsWith(locked+':'))delete obj[k];render();if(!total(own)&&!total(guest))return}const logs=JSON.parse(localStorage.getItem(logKey)||'[]'),now=new Date().toISOString(),newRows=[];Object.entries(own).forEach(([selectionKey,quantity])=>newRows.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,timestamp:now,type:'employee',cardNumber:employee.cardNumber,employeeNumber:employee.employeeNumber,employeeName:employee.employeeName,comment:'',selectionKey,quantity:Number(quantity)}));Object.entries(guest).forEach(([selectionKey,quantity])=>newRows.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,timestamp:now,type:'guest',cardNumber:employee.cardNumber,employeeNumber:employee.employeeNumber,employeeName:employee.employeeName,comment:comment.value,selectionKey,quantity:Number(quantity)}));localStorage.setItem(logKey,JSON.stringify([...logs,...newRows]));sessionStorage.removeItem(sessionKey);clearInterval(timeoutTimer);const count=newRows.reduce((n,r)=>n+r.quantity,0),toast=document.querySelector('#toast');toast.textContent=text[language].saved(count);toast.classList.add('show');setTimeout(()=>location.replace('index.html'),1100)}
function resetTimeout(){timeoutSeconds=60;updateCounter()}function updateCounter(){const counter=document.querySelector('#timeoutCounter');counter.textContent=`${timeoutSeconds} s`;counter.classList.toggle('warning',timeoutSeconds<=15&&timeoutSeconds>5);counter.classList.toggle('urgent',timeoutSeconds<=5)}function timeoutLogout(){sessionStorage.removeItem(sessionKey);location.replace('index.html')}function startTimeout(){updateCounter();timeoutTimer=setInterval(()=>{timeoutSeconds-=1;updateCounter();if(timeoutSeconds<=0){clearInterval(timeoutTimer);timeoutLogout()}},1000)}
['pointerdown','keydown','touchstart'].forEach(eventName=>document.addEventListener(eventName,resetTimeout,{passive:true}));document.querySelector('#kioskSave').addEventListener('click',finish);document.querySelector('#logoutButton').addEventListener('click',timeoutLogout);const today=menu.find(d=>d.id===localDateKey(new Date()));if(today)expandedDays.add(today.id);applyText();render();startTimeout();
