const sessionKey="lunch-poc-card-session-v8",logKey="lunch-poc-kiosk-order-log-v8",languageKey="lunch-poc-kiosk-language-v10";
let employee;try{employee=JSON.parse(sessionStorage.getItem(sessionKey))}catch{}if(!employee)location.replace('index.html');
let language=localStorage.getItem(languageKey)||'en',mode='own',own={},guest={},initialOwn={},initialGuest={},expandedDays=new Set(),timeoutSeconds=60,timeoutTimer;
const text={
 en:{myLunch:'My lunch',guestLunches:'Guest lunches',orderOwn:'Order your own lunch',orderHint:'Review or change your orders below, then save. The screen returns to card login automatically.',workTask:'Work task / project',workHelp:'Required for guest lunches. Comments are stored exactly as entered.',save:'Save and finish',cancel:'Cancel',noLunch:'No lunches selected',selected:n=>`${n} lunch${n===1?'':'es'} selected`,selectMeal:'No unsaved changes',enterProject:'Enter work task / project for guest lunches',ready:'Unsaved changes',menu:'Lunch menu',saved:n=>`${n} lunch${n===1?'':'es'} saved. Returning to card login…`,locked:'Ordering closed at 08:30',lockedHelp:'Today’s order is visible but can no longer be changed.'},
 sv:{myLunch:'Min lunch',guestLunches:'Gästluncher',orderOwn:'Beställ din egen lunch',orderHint:'Kontrollera eller ändra dina beställningar nedan och spara sedan. Skärmen återgår automatiskt till kortinloggningen.',workTask:'Arbetsuppgift / projekt',workHelp:'Obligatoriskt för gästluncher. Kommentaren sparas exakt som den anges.',save:'Spara och avsluta',cancel:'Avbryt',noLunch:'Inga luncher valda',selected:n=>`${n} lunch${n===1?'':'er'} valda`,selectMeal:'Inga osparade ändringar',enterProject:'Ange arbetsuppgift / projekt för gästluncher',ready:'Osparade ändringar',menu:'Lunchmeny',saved:n=>`${n} lunch${n===1?'':'er'} sparade. Återgår till kortinloggningen…`,locked:'Beställningen stängde 08:30',lockedHelp:'Dagens beställning visas men kan inte längre ändras.'},
 fi:{myLunch:'Oma lounas',guestLunches:'Vieraslounaat',orderOwn:'Tilaa oma lounaasi',orderHint:'Tarkista tai muuta alla olevia tilauksiasi ja tallenna. Näyttö palaa automaattisesti korttikirjautumiseen.',workTask:'Työtehtävä / projekti',workHelp:'Pakollinen vieraslounaille. Kommentti tallennetaan täsmälleen syötetyssä muodossa.',save:'Tallenna ja lopeta',cancel:'Peruuta',noLunch:'Ei valittuja lounaita',selected:n=>`${n} lounas${n===1?'':'ta'} valittu`,selectMeal:'Ei tallentamattomia muutoksia',enterProject:'Anna vieraslounaan työtehtävä / projekti',ready:'Tallentamattomia muutoksia',menu:'Lounaslista',saved:n=>`${n} lounas${n===1?'':'ta'} tallennettu. Palataan korttikirjautumiseen…`,locked:'Tilaus sulkeutui klo 08.30',lockedHelp:'Tämän päivän tilaus näkyy, mutta sitä ei voi enää muuttaa.'}
};
const dayNames={Monday:{sv:'Måndag',fi:'Maanantai'},Tuesday:{sv:'Tisdag',fi:'Tiistai'},Wednesday:{sv:'Onsdag',fi:'Keskiviikko'},Thursday:{sv:'Torstai',fi:'Torstai'},Friday:{sv:'Fredag',fi:'Perjantai'}};
// Correct accidental Swedish Thursday value if this object is edited later.
dayNames.Thursday.sv='Torsdag';
const categoryNames={main:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},main2:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},vegetarian:{en:'Vegetarian',sv:'Vegetarisk',fi:'Kasvisruoka'},soup:{en:'Soup',sv:'Soppa',fi:'Keitto'},salad:{en:'Salad',sv:'Sallad',fi:'Salaatti'},other:{en:'Other',sv:'Övrigt',fi:'Muu'}};
const defaultSalads=[{en:'Vegetarian salad',sv:'Vegetarisk sallad',fi:'Kasvissalaatti',active:true},{en:'Beef salad',sv:'Nötköttssallad',fi:'Naudanlihasalaatti',active:true},{en:'Tuna salad',sv:'Tonfisksallad',fi:'Tonnikalasalaatti',active:true},{en:'Pasta salad with chicken',sv:'Pastasallad med kyckling',fi:'Pastasalaatti kanalla',active:true},{en:'Salmon salad',sv:'Laxsallad',fi:'Lohisalaatti',active:true},{en:'Chicken salad',sv:'Kycklingsallad',fi:'Kanasalaatti',active:true}];
function activeWeek(date){try{const builder=JSON.parse(localStorage.getItem('lunch-poc-menu-builder-v1')),library=JSON.parse(localStorage.getItem('lunch-poc-meal-library-v1'))||[];if(builder?.weeks?.length){const monday=new Date(date);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const cycle=Number(builder.repeatWeeks)||builder.weeks.length,index=((Math.floor((monday-new Date(2026,8,21))/604800000)%cycle)+cycle)%cycle,week=builder.weeks[index]||builder.weeks[0];return{days:['Monday','Tuesday','Wednesday','Thursday','Friday'].map((day,i)=>({day,meals:(week.days?.[i]?.mealIds||[]).map(id=>library.find(m=>m.id===id)).filter(Boolean).map(m=>({type:m.type,names:m.names}))}))}}const c=JSON.parse(localStorage.getItem('lunch-poc-menu-config-v6'))||JSON.parse(localStorage.getItem('lunch-poc-menu-config-v5'));if(c?.weeks?.length){const monday=new Date(date);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));const cycle=Number(c.repeatWeeks)||c.weeks.length,index=((Math.floor((monday-new Date(2026,8,21))/604800000)%cycle)+cycle)%cycle;return c.weeks[index]||c.weeks[0]}}catch{}return{days:['Monday','Tuesday','Wednesday','Thursday','Friday'].map(day=>({day,meals:[{type:'main',names:{en:'Meatballs with mashed potatoes',sv:'Köttbullar med potatismos',fi:'Lihapullat ja perunamuusi'}},{type:'vegetarian',names:{en:'Vegetable lasagne',sv:'Grönsakslasagne',fi:'Kasvislasagne'}},{type:'soup',names:{en:'Tomato soup',sv:'Tomatsoppa',fi:'Tomaattikeitto'}}]}))}}
function salads(){try{const saved=JSON.parse(localStorage.getItem('lunch-poc-salads-v5'));return(saved?.length?saved:defaultSalads).filter(s=>s.active!==false)}catch{return defaultSalads}}
function mealName(names){return(names?.[language]||names?.en||'').trim()}function category(type){return categoryNames[type]?.[language]||categoryNames[type]?.en||type}
const simulationLabels={en:'POC: Simulate Friday',sv:'POC: Simulera fredag',fi:'POC: Simuloi perjantai'};
function localDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function effectiveToday(){const d=new Date();d.setHours(0,0,0,0);if(document.querySelector('#simulateFriday')?.checked)d.setDate(d.getDate()+((5-d.getDay()+7)%7));return d}
function deadlinePassed(){const now=new Date();return now.getHours()>8||(now.getHours()===8&&now.getMinutes()>=30)}
function dayLocked(id){return id===localDateKey(effectiveToday())&&deadlinePassed()}
function shownDates(){const today=effectiveToday(),weekday=today.getDay();if(weekday===0||weekday===6){const next=new Date(today);next.setDate(today.getDate()+((8-weekday)%7));return Array.from({length:5},(_,i)=>{const d=new Date(next);d.setDate(next.getDate()+i);return d})}const dates=[],friday=new Date(today);friday.setDate(today.getDate()+(5-weekday));for(let d=new Date(today);d<=friday;d.setDate(d.getDate()+1))dates.push(new Date(d));if(weekday===5){const nextMonday=new Date(today);nextMonday.setDate(today.getDate()+3);for(let i=0;i<5;i++){const d=new Date(nextMonday);d.setDate(nextMonday.getDate()+i);dates.push(d)}}return dates}
function buildMenu(){return shownDates().map(dt=>{const week=activeWeek(dt),i=(dt.getDay()+6)%7,d=week.days[i];return{id:localDateKey(dt),day:language==='en'?d.day:(dayNames[d.day]?.[language]||d.day),date:String(dt.getDate()).padStart(2,'0')+'.'+String(dt.getMonth()+1).padStart(2,'0'),meals:[...d.meals.filter(m=>mealName(m.names)).map(m=>({name:mealName(m.names),category:category(m.type)})),...salads().filter(s=>mealName(s)).map(s=>({name:mealName(s),category:category('salad')}))]}})}
function readLogs(){try{const value=JSON.parse(localStorage.getItem(logKey));return Array.isArray(value)?value:[]}catch{return[]}}
function selectionDate(selectionKey){return String(selectionKey||'').slice(0,String(selectionKey||'').lastIndexOf(':'))}
function visibleDateSet(){return new Set(menu.map(day=>day.id))}
function loadExistingOrders(){const dates=visibleDateSet(),loadedOwn={},loadedGuest={};let latestGuestComment='',latestGuestTime='';for(const row of readLogs()){if(String(row?.employeeNumber)!==String(employee.employeeNumber)||!['employee','guest'].includes(row.type)||!dates.has(selectionDate(row.selectionKey)))continue;const target=row.type==='employee'?loadedOwn:loadedGuest;target[row.selectionKey]=(target[row.selectionKey]||0)+(Number(row.quantity)||0);if(row.type==='guest'&&String(row.comment||'').trim()&&String(row.timestamp||'')>=latestGuestTime){latestGuestTime=String(row.timestamp||'');latestGuestComment=String(row.comment)}}own=loadedOwn;guest=loadedGuest;initialOwn=structuredClone(own);initialGuest=structuredClone(guest);comment.value=latestGuestComment}
function key(d,i){return`${d}:${i}`}function orders(){return mode==='own'?own:guest}function total(obj=orders()){return Object.values(obj).reduce((a,b)=>a+Number(b),0)}
function normalized(obj){return Object.fromEntries(Object.entries(obj).filter(([,value])=>Number(value)>0).sort(([a],[b])=>a.localeCompare(b)))}
function dirty(){return JSON.stringify(normalized(own))!==JSON.stringify(normalized(initialOwn))||JSON.stringify(normalized(guest))!==JSON.stringify(normalized(initialGuest))}
let menu=buildMenu();const box=document.querySelector('#kioskWeek'),guestField=document.querySelector('#guestField'),comment=document.querySelector('#guestComment'),languageSelect=document.querySelector('#kioskLanguage');document.querySelector('#employeeName').textContent=employee.employeeName;document.querySelector('#employeeNumber').textContent=`Employee ${employee.employeeNumber}`;languageSelect.value=language;
function applyText(){const t=text[language];document.querySelector('[data-mode="own"]').textContent=t.myLunch;document.querySelector('[data-mode="guest"]').textContent=t.guestLunches;document.querySelector('#ownNote strong').textContent=t.orderOwn;document.querySelector('#ownNote span').textContent=t.orderHint;document.querySelector('label[for="guestComment"]').childNodes[0].textContent=t.workTask+' ';document.querySelector('#guestField small').textContent=t.workHelp;document.querySelector('#kioskSave').textContent=t.save;document.querySelector('#logoutButton').textContent=t.cancel;document.querySelector('#simulateFridayLabel').textContent=simulationLabels[language]||simulationLabels.en}
function render(){const current=orders();box.innerHTML=menu.map(d=>{const open=expandedDays.has(d.id),locked=dayLocked(d.id),dayCount=d.meals.reduce((n,_,i)=>n+(current[key(d.id,i)]||0),0);return`<article class="day ${open?'open':''} ${locked?'deadline-locked':''}" data-day="${d.id}"><button class="day-toggle" type="button" aria-expanded="${open}"><span class="chevron"></span><span class="day-name"><strong>${d.day} ${d.date}</strong><span>${locked?text[language].locked:text[language].menu}</span></span><span class="day-total ${dayCount?'has-orders':''}">🍴 ${dayCount}</span></button><div class="day-content">${locked?`<div class="deadline-lock-note">${text[language].lockedHelp}</div>`:''}${d.meals.map((m,i)=>`<div class="meal-row"><div class="meal-name"><strong>${m.name}</strong><span>${m.category}</span></div><div class="stepper" data-index="${i}"><button class="minus" type="button" ${(locked||!current[key(d.id,i)])?'disabled':''}>−</button><output>${current[key(d.id,i)]||0}</output><button class="plus" type="button" ${locked?'disabled':''}>+</button></div></div>`).join('')}</div></article>`}).join('');update()}
box.addEventListener('click',e=>{resetTimeout();const toggle=e.target.closest('.day-toggle');if(toggle){const id=toggle.closest('.day').dataset.day;expandedDays.has(id)?expandedDays.delete(id):expandedDays.add(id);render();return}const b=e.target.closest('.stepper button');if(!b)return;const day=b.closest('.day').dataset.day;if(dayLocked(day)){showToast(text[language].locked);return}const i=+b.closest('.stepper').dataset.index,k=key(day,i),obj=orders();obj[k]=Math.max(0,(obj[k]||0)+(b.classList.contains('plus')?1:-1));if(!obj[k])delete obj[k];expandedDays.add(day);render()});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{resetTimeout();mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));guestField.hidden=mode!=='guest';render()}));
comment.addEventListener('input',()=>{resetTimeout();update()});
languageSelect.addEventListener('change',()=>{resetTimeout();language=languageSelect.value;localStorage.setItem(languageKey,language);menu=buildMenu();applyText();render()});
document.querySelector('#simulateFriday').addEventListener('change',()=>{resetTimeout();menu=buildMenu();expandedDays.clear();loadExistingOrders();const today=menu.find(d=>d.id===localDateKey(effectiveToday()));if(today)expandedDays.add(today.id);render()});
function update(){const ownCount=total(own),guestCount=total(guest),all=ownCount+guestCount,t=text[language],hasChanges=dirty(),validGuest=!guestCount||comment.value.trim();document.querySelector('#kioskSummary').textContent=all?t.selected(all):t.noLunch;document.querySelector('#kioskStatus').textContent=guestCount&&!validGuest?t.enterProject:hasChanges?t.ready:t.selectMeal;document.querySelector('#kioskSave').disabled=!hasChanges||!validGuest}
function finish(){const dates=visibleDateSet(),logs=readLogs(),remaining=logs.filter(row=>String(row?.employeeNumber)!==String(employee.employeeNumber)||!['employee','guest'].includes(row.type)||!dates.has(selectionDate(row.selectionKey))),now=new Date().toISOString(),newRows=[];Object.entries(own).forEach(([selectionKey,quantity])=>{if(dayLocked(selectionDate(selectionKey)))return;newRows.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,timestamp:now,type:'employee',cardNumber:employee.cardNumber,employeeNumber:employee.employeeNumber,employeeName:employee.employeeName,comment:'',selectionKey,quantity:Number(quantity)})});Object.entries(guest).forEach(([selectionKey,quantity])=>{if(dayLocked(selectionDate(selectionKey)))return;newRows.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,timestamp:now,type:'guest',cardNumber:employee.cardNumber,employeeNumber:employee.employeeNumber,employeeName:employee.employeeName,comment:comment.value.trim(),selectionKey,quantity:Number(quantity)})});
// Preserve this employee's locked order for today while replacing editable visible dates.
const lockedRows=logs.filter(row=>String(row?.employeeNumber)===String(employee.employeeNumber)&&['employee','guest'].includes(row.type)&&dates.has(selectionDate(row.selectionKey))&&dayLocked(selectionDate(row.selectionKey)));
localStorage.setItem(logKey,JSON.stringify([...remaining,...lockedRows,...newRows]));sessionStorage.removeItem(sessionKey);clearInterval(timeoutTimer);const count=newRows.reduce((n,r)=>n+r.quantity,0)+lockedRows.reduce((n,r)=>n+(Number(r.quantity)||0),0),toast=document.querySelector('#toast');toast.textContent=text[language].saved(count);toast.classList.add('show');setTimeout(()=>location.replace('index.html'),1100)}
let toastTimer;function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function resetTimeout(){timeoutSeconds=60;updateCounter()}function updateCounter(){const counter=document.querySelector('#timeoutCounter');counter.textContent=`${timeoutSeconds} s`;counter.classList.toggle('warning',timeoutSeconds<=15&&timeoutSeconds>5);counter.classList.toggle('urgent',timeoutSeconds<=5)}function timeoutLogout(){sessionStorage.removeItem(sessionKey);location.replace('index.html')}function startTimeout(){updateCounter();timeoutTimer=setInterval(()=>{timeoutSeconds-=1;updateCounter();if(timeoutSeconds<=0){clearInterval(timeoutTimer);timeoutLogout()}},1000)}
['pointerdown','keydown','touchstart'].forEach(eventName=>document.addEventListener(eventName,resetTimeout,{passive:true}));document.querySelector('#kioskSave').addEventListener('click',finish);document.querySelector('#logoutButton').addEventListener('click',timeoutLogout);loadExistingOrders();for(const day of menu)if(Object.keys(own).some(k=>k.startsWith(day.id+':'))||Object.keys(guest).some(k=>k.startsWith(day.id+':')))expandedDays.add(day.id);const today=menu.find(d=>d.id===localDateKey(new Date()));if(today)expandedDays.add(today.id);applyText();render();startTimeout();
