(() => {
  const KEY = 'lunch-poc-admin-language-v1';
  const dictionaries = {
    sv: {'Load example menu':'Ladda exempelmeny','Replace the current menu and library with the four-week example?':'Ersätt den nuvarande menyn och biblioteket med fyraveckorsexemplet?','Example menu loaded':'Exempelmenyn laddades','Available dishes':'Tillgängliga maträtter','Build the menu from the dish library':'Bygg menyn från maträttsbiblioteket','Drag a dish to a day, or select a dish and use Add.':'Dra en maträtt till en dag, eller välj en maträtt och tryck Lägg till.','All':'Alla','Add':'Lägg till','dish':'maträtt','dishes':'maträtter','week menu':'veckorsmeny','or select a dish and press Add':'eller välj en maträtt och tryck Lägg till','The Menu Builder reuses the saved translations.':'Menybyggaren återanvänder de sparade översättningarna.','Dishes':'Maträtter','Used when building weekly menus':'Används när veckomenyer byggs','Delete this dish?':'Radera denna maträtt?','All categories':'Alla kategorier','Search':'Sök',
      'Lunch administration':'Lunchadministration','Menu, kitchen and reporting':'Meny, kök och rapportering','Ordering':'Beställning','Administration':'Administration','Lunch service':'Lunchservering','Maintain menus, review orders and manage employee data.':'Hantera menyer, granska beställningar och administrera personaluppgifter.','Weekly menu':'Veckomeny','Maintain the rolling multilingual menu.':'Hantera den rullande flerspråkiga menyn.','Meal library':'Maträttsbibliotek','Create and maintain reusable dishes.':'Skapa och hantera återanvändbara maträtter.','Salad menu':'Salladsmeny','Maintain the fixed daily salad selection.':'Hantera det fasta dagliga salladsutbudet.','Daily kitchen summary':'Daglig kökssammanfattning','Production totals, names and guest details.':'Produktionsantal, namn och gästdetaljer.','Weekly summary':'Veckosammanfattning','Employee and guest totals with CSV export.':'Antal personal- och gästluncher med CSV-export.','Employee admin':'Personaladministration','Employee numbers and card mappings.':'Personalnummer och kortkopplingar.','Order Explorer':'Beställningsutforskare','Explore orders by employee or meal.':'Utforska beställningar enligt person eller maträtt.','Bulla products':'Bulla-produkter','Products, pictures, prices and display order.':'Produkter, bilder, priser och visningsordning.','Bulla report':'Bulla-rapport','Purchases grouped by employee.':'Inköp grupperade enligt person.','Bulla kiosk':'Bulla-kiosk','Uses the same employee and card directory.':'Använder samma personal- och kortregister.',
      'Weekly menu administration':'Administration av veckomeny','Menu builder':'Menybyggare','Build the rolling menu from reusable dishes':'Bygg den rullande menyn av återanvändbara maträtter','Save':'Spara','Saved':'Sparad','Menu cycle':'Menycykel','Number of weeks':'Antal veckor','The menu starts again after the last week.':'Menyn börjar om efter den sista veckan.','Dish library':'Maträttsbibliotek','Search dishes':'Sök maträtter','Search by name or category':'Sök enligt namn eller kategori','Drag dishes to a day. The translations are already stored in the library.':'Dra maträtter till en dag. Översättningarna finns redan i biblioteket.','Editing':'Redigerar','Copy previous week':'Kopiera föregående vecka','Clear day':'Töm dagen','No dishes assigned':'Inga maträtter valda','Drop dishes here':'Släpp maträtter här','Remove':'Ta bort','Open meal library':'Öppna maträttsbiblioteket','Four-week menu':'Fyraveckorsmeny','Week':'Vecka','Monday':'Måndag','Tuesday':'Tisdag','Wednesday':'Onsdag','Thursday':'Torsdag','Friday':'Fredag','Main dish':'Huvudrätt','Vegetarian':'Vegetarisk','Soup':'Soppa','Other':'Övrigt','Active':'Aktiv','Inactive':'Inaktiv','Category':'Kategori','English':'Engelska','Swedish':'Svenska','Finnish':'Finska','Dish names':'Maträttens namn','Add dish':'Lägg till maträtt','New dish':'Ny maträtt','Delete dish':'Radera maträtt','Meal library administration':'Administration av maträttsbibliotek','Reusable multilingual dishes':'Återanvändbara flerspråkiga maträtter','Add each dish once in English, Swedish and Finnish. Menu Builder only uses the saved dish.':'Lägg till varje maträtt en gång på engelska, svenska och finska. Menybyggaren använder sedan den sparade maträtten.','No matching dishes':'Inga matchande maträtter','Dish library saved':'Maträttsbiblioteket sparades','Menu saved':'Menyn sparades','Previous week copied':'Föregående vecka kopierades','Week 1 has no previous week':'Vecka 1 har ingen föregående vecka',
      'Fixed daily selection':'Fast dagligt utbud','Salads available every day':'Sallader som finns varje dag','These salads are kept outside the weekly menu and added automatically.':'Dessa sallader hanteras separat från veckomenyn och läggs till automatiskt.','+ Add salad':'+ Lägg till sallad','Three-language names':'Namn på tre språk','Enter the customer-facing name in English, Swedish and Finnish.':'Ange namnet som visas för användarna på engelska, svenska och finska.','Salad menu saved':'Salladsmenyn sparades',
      'Employee administration':'Personaladministration','Card and employee matching':'Koppling mellan kort och personal','Open kiosk':'Öppna kiosken','Card directory':'Kortregister','Employees':'Personal','Add employees manually or import a CSV file.':'Lägg till personal manuellt eller importera en CSV-fil.','Import CSV':'Importera CSV','+ Add employee':'+ Lägg till person','CSV columns':'CSV-kolumner','Existing card numbers are updated; new card numbers are added.':'Befintliga kortnummer uppdateras och nya läggs till.','Card number':'Kortnummer','Employee number':'Personalnummer','Employee name':'Namn','Actions':'Åtgärder','Edit':'Redigera','Delete':'Radera','Add employee':'Lägg till person','Edit employee':'Redigera person','Cancel':'Avbryt','Save employee':'Spara person','Employee saved':'Personen sparades','Employee deleted':'Personen raderades','Card number already exists':'Kortnumret finns redan',
      'Pictures, prices and display order':'Bilder, priser och visningsordning','Product administration':'Produktadministration','Products':'Produkter','Edit product names in English, Swedish and Finnish. Changes are saved only when you press Save.':'Redigera produktnamn på engelska, svenska och finska. Ändringarna sparas först när du trycker på Spara.','+ Add product':'+ Lägg till produkt','Pictures in the POC':'Bilder i POC-versionen','Change picture':'Byt bild','Product names':'Produktnamn','Price':'Pris','Status':'Status','Fallback':'Reservvärde','Icon':'Ikon','Move up':'Flytta upp','Move down':'Flytta ner','Delete product':'Radera produkt','Unsaved':'Osparad','Product list saved':'Produktlistan sparades',
      'Purchases by employee':'Inköp per person','Export CSV':'Exportera CSV','Weekly':'Vecka','Monthly':'Månad','Period':'Period','Search':'Sök','Employee or product':'Person eller produkt','Purchases':'Inköp','Total':'Totalt','Employee purchases':'Personalens inköp','Click an employee to show individual purchases and products.':'Klicka på en person för att visa enskilda inköp och produkter.','No matching purchases':'Inga matchande inköp',
      'Production totals and names':'Produktionsantal och namn','Print':'Skriv ut','Day':'Dag','Find employee':'Sök person','Search name or employee number':'Sök namn eller personalnummer','Include demo orders':'Inkludera demobeställningar','Total lunches':'Luncher totalt','Employee':'Personal','Guest':'Gäst','Meal choices':'Maträtter','Daily totals':'Dagliga antal','Click a meal to show who ordered it':'Klicka på en maträtt för att visa vem som beställt','Final after 08:30':'Slutligt efter 08:30','Guest lunch details':'Detaljer för gästluncher','Ordering employee and exact comment':'Beställande person och exakt kommentar','No guest orders':'Inga gästbeställningar',
      'Employee and guest lunch counts':'Antal personal- och gästluncher','Include demo data':'Inkludera demodata','Employee lunches':'Personalluncher','Guest lunches':'Gästluncher','Guest comments':'Gästkommentarer','One row per employee. Meal choices are deliberately not shown.':'En rad per person. Maträttsval visas avsiktligt inte.','Export employee CSV':'Exportera personal-CSV','Work task / project comment':'Arbetsuppgift / projektkommentar','Lunches':'Luncher','Comments remain separate exactly as entered. No spelling or project matching is applied.':'Kommentarerna hålls separata exakt som de skrivits. Ingen stavnings- eller projektmatchning görs.','Export guest CSV':'Exportera gäst-CSV',
      'Who ordered what?':'Vem beställde vad?','Search employee, number, meal or guest comment':'Sök person, nummer, maträtt eller gästkommentar','By employee':'Enligt person','By meal':'Enligt maträtt','Orders by employee':'Beställningar enligt person','Select an employee to see daily details.':'Välj en person för att visa dagliga detaljer.','Orders by meal':'Beställningar enligt maträtt','Select a meal to see names, dates and quantities.':'Välj en maträtt för att visa namn, datum och antal.','No matching orders':'Inga matchande beställningar'
    },
    fi: {'Load example menu':'Lataa esimerkkiruokalista','Replace the current menu and library with the four-week example?':'Korvataanko nykyinen ruokalista ja kirjasto neljän viikon esimerkillä?','Example menu loaded':'Esimerkkiruokalista ladattiin','Available dishes':'Saatavilla olevat ruokalajit','Build the menu from the dish library':'Rakenna ruokalista ruokalajikirjastosta','Drag a dish to a day, or select a dish and use Add.':'Vedä ruokalaji päivälle tai valitse ruokalaji ja paina Lisää.','All':'Kaikki','Add':'Lisää','dish':'ruokalaji','dishes':'ruokalajia','week menu':'viikon ruokalista','or select a dish and press Add':'tai valitse ruokalaji ja paina Lisää','The Menu Builder reuses the saved translations.':'Ruokalistan rakentaja käyttää tallennettuja käännöksiä.','Dishes':'Ruokalajit','Used when building weekly menus':'Käytetään viikkoruokalistojen rakentamiseen','Delete this dish?':'Poistetaanko tämä ruokalaji?','All categories':'Kaikki luokat','Search':'Haku',
      'Lunch administration':'Lounashallinta','Menu, kitchen and reporting':'Ruokalista, keittiö ja raportointi','Ordering':'Tilaaminen','Administration':'Hallinta','Lunch service':'Lounaspalvelu','Maintain menus, review orders and manage employee data.':'Ylläpidä ruokalistoja, tarkastele tilauksia ja hallitse henkilötietoja.','Weekly menu':'Viikkoruokalista','Maintain the rolling multilingual menu.':'Ylläpidä kiertävää monikielistä ruokalistaa.','Meal library':'Ruokalajikirjasto','Create and maintain reusable dishes.':'Luo ja ylläpidä uudelleenkäytettäviä ruokalajeja.','Salad menu':'Salaattilista','Maintain the fixed daily salad selection.':'Ylläpidä päivittäistä salaattivalikoimaa.','Daily kitchen summary':'Keittiön päiväyhteenveto','Production totals, names and guest details.':'Valmistusmäärät, nimet ja vierastiedot.','Weekly summary':'Viikkoyhteenveto','Employee and guest totals with CSV export.':'Henkilöstö- ja vieraslounaat sekä CSV-vienti.','Employee admin':'Henkilöstöhallinta','Employee numbers and card mappings.':'Henkilönumerot ja korttikytkennät.','Order Explorer':'Tilausselain','Explore orders by employee or meal.':'Tarkastele tilauksia henkilön tai ruokalajin mukaan.','Bulla products':'Bulla-tuotteet','Products, pictures, prices and display order.':'Tuotteet, kuvat, hinnat ja näyttöjärjestys.','Bulla report':'Bulla-raportti','Purchases grouped by employee.':'Ostot henkilöittäin.','Bulla kiosk':'Bulla-kioski','Uses the same employee and card directory.':'Käyttää samaa henkilö- ja korttirekisteriä.',
      'Weekly menu administration':'Viikkoruokalistan hallinta','Menu builder':'Ruokalistan rakentaja','Build the rolling menu from reusable dishes':'Rakenna kiertävä ruokalista uudelleenkäytettävistä ruokalajeista','Save':'Tallenna','Saved':'Tallennettu','Menu cycle':'Ruokalistakierto','Number of weeks':'Viikkojen määrä','The menu starts again after the last week.':'Ruokalista alkaa uudelleen viimeisen viikon jälkeen.','Dish library':'Ruokalajikirjasto','Search dishes':'Hae ruokalajeja','Search by name or category':'Hae nimen tai luokan mukaan','Drag dishes to a day. The translations are already stored in the library.':'Vedä ruokalajit päivälle. Käännökset on jo tallennettu kirjastoon.','Editing':'Muokataan','Copy previous week':'Kopioi edellinen viikko','Clear day':'Tyhjennä päivä','No dishes assigned':'Ei valittuja ruokalajeja','Drop dishes here':'Pudota ruokalajit tähän','Remove':'Poista','Open meal library':'Avaa ruokalajikirjasto','Four-week menu':'Neljän viikon ruokalista','Week':'Viikko','Monday':'Maanantai','Tuesday':'Tiistai','Wednesday':'Keskiviikko','Thursday':'Torstai','Friday':'Perjantai','Main dish':'Pääruoka','Vegetarian':'Kasvisruoka','Soup':'Keitto','Other':'Muu','Active':'Aktiivinen','Inactive':'Ei aktiivinen','Category':'Luokka','English':'Englanti','Swedish':'Ruotsi','Finnish':'Suomi','Dish names':'Ruokalajin nimet','Add dish':'Lisää ruokalaji','New dish':'Uusi ruokalaji','Delete dish':'Poista ruokalaji','Meal library administration':'Ruokalajikirjaston hallinta','Reusable multilingual dishes':'Uudelleenkäytettävät monikieliset ruokalajit','Add each dish once in English, Swedish and Finnish. Menu Builder only uses the saved dish.':'Lisää jokainen ruokalaji kerran englanniksi, ruotsiksi ja suomeksi. Ruokalistan rakentaja käyttää tallennettua ruokalajia.','No matching dishes':'Ei vastaavia ruokalajeja','Dish library saved':'Ruokalajikirjasto tallennettiin','Menu saved':'Ruokalista tallennettiin','Previous week copied':'Edellinen viikko kopioitiin','Week 1 has no previous week':'Viikolla 1 ei ole edellistä viikkoa',
      'Fixed daily selection':'Kiinteä päivittäinen valikoima','Salads available every day':'Päivittäin saatavat salaatit','These salads are kept outside the weekly menu and added automatically.':'Salaatit ylläpidetään erillään viikkoruokalistasta ja lisätään automaattisesti.','+ Add salad':'+ Lisää salaatti','Three-language names':'Nimet kolmella kielellä','Enter the customer-facing name in English, Swedish and Finnish.':'Anna asiakkaalle näkyvä nimi englanniksi, ruotsiksi ja suomeksi.','Salad menu saved':'Salaattilista tallennettiin',
      'Employee administration':'Henkilöstöhallinta','Card and employee matching':'Kortin ja henkilön yhdistäminen','Open kiosk':'Avaa kioski','Card directory':'Korttirekisteri','Employees':'Henkilöstö','Add employees manually or import a CSV file.':'Lisää henkilöitä manuaalisesti tai tuo CSV-tiedosto.','Import CSV':'Tuo CSV','+ Add employee':'+ Lisää henkilö','CSV columns':'CSV-sarakkeet','Existing card numbers are updated; new card numbers are added.':'Nykyiset korttinumerot päivitetään ja uudet lisätään.','Card number':'Korttinumero','Employee number':'Henkilönumero','Employee name':'Nimi','Actions':'Toiminnot','Edit':'Muokkaa','Delete':'Poista','Add employee':'Lisää henkilö','Edit employee':'Muokkaa henkilöä','Cancel':'Peruuta','Save employee':'Tallenna henkilö','Employee saved':'Henkilö tallennettiin','Employee deleted':'Henkilö poistettiin','Card number already exists':'Korttinumero on jo käytössä',
      'Pictures, prices and display order':'Kuvat, hinnat ja näyttöjärjestys','Product administration':'Tuotehallinta','Products':'Tuotteet','Edit product names in English, Swedish and Finnish. Changes are saved only when you press Save.':'Muokkaa tuotenimiä englanniksi, ruotsiksi ja suomeksi. Muutokset tallennetaan vasta Tallenna-painikkeella.','+ Add product':'+ Lisää tuote','Pictures in the POC':'Kuvat POC-versiossa','Change picture':'Vaihda kuva','Product names':'Tuotenimet','Price':'Hinta','Status':'Tila','Fallback':'Varavaihtoehto','Icon':'Kuvake','Move up':'Siirrä ylös','Move down':'Siirrä alas','Delete product':'Poista tuote','Unsaved':'Tallentamaton','Product list saved':'Tuotelista tallennettiin',
      'Purchases by employee':'Ostot henkilöittäin','Export CSV':'Vie CSV','Weekly':'Viikko','Monthly':'Kuukausi','Period':'Jakso','Search':'Haku','Employee or product':'Henkilö tai tuote','Purchases':'Ostot','Total':'Yhteensä','Employee purchases':'Henkilöstön ostot','Click an employee to show individual purchases and products.':'Näytä yksittäiset ostot ja tuotteet napsauttamalla henkilöä.','No matching purchases':'Ei vastaavia ostoja',
      'Production totals and names':'Valmistusmäärät ja nimet','Print':'Tulosta','Day':'Päivä','Find employee':'Hae henkilöä','Search name or employee number':'Hae nimeä tai henkilönumeroa','Include demo orders':'Sisällytä demotilaukset','Total lunches':'Lounaita yhteensä','Employee':'Henkilöstö','Guest':'Vieras','Meal choices':'Ruokalajit','Daily totals':'Päivän määrät','Click a meal to show who ordered it':'Näytä tilaajat napsauttamalla ruokalajia','Final after 08:30':'Lopullinen klo 08.30 jälkeen','Guest lunch details':'Vieraslounaiden tiedot','Ordering employee and exact comment':'Tilaava henkilö ja tarkka kommentti','No guest orders':'Ei vierastilauksia',
      'Employee and guest lunch counts':'Henkilöstö- ja vieraslounaiden määrät','Include demo data':'Sisällytä demotiedot','Employee lunches':'Henkilöstölounaat','Guest lunches':'Vieraslounaat','Guest comments':'Vieraskommentit','One row per employee. Meal choices are deliberately not shown.':'Yksi rivi henkilöä kohden. Ruokalajivalintoja ei tarkoituksella näytetä.','Export employee CSV':'Vie henkilöstö-CSV','Work task / project comment':'Työtehtävä / projektikommentti','Lunches':'Lounaat','Comments remain separate exactly as entered. No spelling or project matching is applied.':'Kommentit pidetään erillään täsmälleen kirjoitetussa muodossa. Oikeinkirjoitusta tai projekteja ei yhdistetä.','Export guest CSV':'Vie vieras-CSV',
      'Who ordered what?':'Kuka tilasi mitä?','Search employee, number, meal or guest comment':'Hae henkilöä, numeroa, ruokalajia tai vieraskommenttia','By employee':'Henkilöittäin','By meal':'Ruokalajeittain','Orders by employee':'Tilaukset henkilöittäin','Select an employee to see daily details.':'Valitse henkilö nähdäksesi päivittäiset tiedot.','Orders by meal':'Tilaukset ruokalajeittain','Select a meal to see names, dates and quantities.':'Valitse ruokalaji nähdäksesi nimet, päivät ja määrät.','No matching orders':'Ei vastaavia tilauksia'
    }
  };
  const originals = new WeakMap();
  function lang(){return localStorage.getItem(KEY)||'sv'}
  function t(text,l=lang()){return l==='en'?text:(dictionaries[l]?.[text]||text)}
  function translate(root=document){
    const l=lang(); document.documentElement.lang=l;
    root.querySelectorAll?.('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;el.textContent=t(k,l)});
    root.querySelectorAll?.('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder,l)});
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;
    while(n=walker.nextNode()){
      if(['SCRIPT','STYLE','CODE'].includes(n.parentElement?.tagName))continue;
      if(!originals.has(n)) originals.set(n,n.nodeValue);
      const base=originals.get(n),trim=base.trim(); if(!trim)continue;
      const translated=t(trim,l); if(translated!==trim)n.nodeValue=base.replace(trim,translated); else if(l==='en')n.nodeValue=base;
    }
    root.querySelectorAll?.('input[placeholder]').forEach(el=>{if(!el.dataset.originalPlaceholder)el.dataset.originalPlaceholder=el.placeholder;el.placeholder=t(el.dataset.originalPlaceholder,l)});
    document.querySelectorAll('.admin-language').forEach(x=>x.value=l);
  }
  function install(){
    document.querySelectorAll('.app-header').forEach(header=>{
      if(header.querySelector('.admin-language'))return;
      const select=document.createElement('select');select.className='language-select admin-language';select.setAttribute('aria-label','Language');select.innerHTML='<option value="en">EN</option><option value="sv">SV</option><option value="fi">FI</option>';select.value=lang();
      const last=header.lastElementChild;header.insertBefore(select,last || null);
      select.addEventListener('change',()=>{localStorage.setItem(KEY,select.value);translate(document);document.dispatchEvent(new CustomEvent('admin-language-changed',{detail:{language:select.value}}))});
    }); translate(document);
    new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)translate(n)}))).observe(document.body,{childList:true,subtree:true});
  }
  window.AdminI18n={t,lang,translate};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install):install();
})();
