const KEY='bulla-poc-order-log-v1';let expanded=new Set(),current=[],period='week';
function read(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}
function localKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseKey(v){const [y,m,d]=String(v).split('-').map(Number);return new Date(y,m-1,d)}
function mondayOf(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function money(c){return new Intl.NumberFormat('fi-FI',{style:'currency',currency:'EUR'}).format(Number(c||0)/100)}
function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function dateText(d){return d.toLocaleDateString('fi-FI')}
function availablePeriods(){const orders=read(),dates=orders.map(o=>new Date(o.timestamp)).filter(d=>!Number.isNaN(d.valueOf()));dates.push(new Date());const keys=new Map();dates.forEach(d=>{if(period==='week'){const start=mondayOf(d),end=new Date(start);end.setDate(start.getDate()+6);keys.set(localKey(start),`${dateText(start)} – ${dateText(end)}`)}else{const start=new Date(d.getFullYear(),d.getMonth(),1);keys.set(localKey(start),start.toLocaleDateString('en-GB',{month:'long',year:'numeric'}))}});return [...keys.entries()].sort((a,b)=>b[0].localeCompare(a[0]))}
function populateHistory(){const previous=historySelect.value,options=availablePeriods();historySelect.innerHTML=options.map(([value,label])=>`<option value="${value}">${esc(label)}</option>`).join('');if(options.some(x=>x[0]===previous))historySelect.value=previous}
function range(){const start=parseKey(historySelect.value),end=new Date(start);if(period==='week')end.setDate(start.getDate()+6);else end.setMonth(start.getMonth()+1,0);end.setHours(23,59,59,999);return{start,end}}
function filtered(){if(!historySelect.value)return[];const {start,end}=range(),q=search.value.trim().toLowerCase();return read().filter(o=>{const d=new Date(o.timestamp),text=[o.employeeName,o.employeeNumber,...(o.lines||[]).map(x=>x.productName)].join(' ').toLowerCase();return d>=start&&d<=end&&(!q||text.includes(q))})}
function grouped(){const map=new Map();current.forEach(o=>{const key=`${o.employeeNumber}|${o.employeeName}`;if(!map.has(key))map.set(key,[]);map.get(key).push(o)});return map}
function render(){current=filtered();const map=grouped();reportRows.innerHTML=[...map].sort((a,b)=>a[1][0].employeeName.localeCompare(b[1][0].employeeName)).map(([key,orders])=>{const open=expanded.has(key),total=orders.reduce((s,o)=>s+Number(o.totalCents||0),0),items=orders.reduce((s,o)=>s+(o.lines||[]).reduce((n,l)=>n+Number(l.quantity||0),0),0);return `<article class="explorer-group"><button class="explorer-group-button" data-key="${esc(key)}"><span><strong>${esc(orders[0].employeeName)}</strong><small>Employee ${esc(orders[0].employeeNumber)} · ${items} products · ${money(total)}</small></span><b>${open?'−':'+'}</b></button><div class="explorer-details" ${open?'':'hidden'}>${orders.sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).map(o=>`<section class="explorer-day"><h3>${new Date(o.timestamp).toLocaleString('fi-FI')}</h3>${(o.lines||[]).map(l=>`<div class="explorer-order"><span><strong>${esc(l.productName)}</strong><small>${l.quantity} × ${money(l.unitPriceCents)}</small></span><b>${money(l.lineTotalCents)}</b></div>`).join('')}</section>`).join('')}</div></article>`}).join('')||'<div class="empty-state">No matching purchases</div>';purchaseCount.textContent=current.length;productCount.textContent=current.reduce((s,o)=>s+(o.lines||[]).reduce((n,l)=>n+Number(l.quantity||0),0),0);grandTotal.textContent=money(current.reduce((s,o)=>s+Number(o.totalCents||0),0))}
reportRows.onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;expanded.has(b.dataset.key)?expanded.delete(b.dataset.key):expanded.add(b.dataset.key);render()};
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;expanded.clear();document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));populateHistory();render()});historySelect.onchange=()=>{expanded.clear();render()};search.oninput=render;
function cell(v){const s=String(v);return s.includes(';')||s.includes('"')||s.includes('\n')||s.includes('\r')?'"'+s.replaceAll('"','""')+'"':s}
exportCsv.onclick=()=>{const rows=[['Employee number','Name','Total']];[...grouped().values()].sort((a,b)=>a[0].employeeName.localeCompare(b[0].employeeName)).forEach(orders=>rows.push([orders[0].employeeNumber,orders[0].employeeName,(orders.reduce((s,o)=>s+Number(o.totalCents||0),0)/100).toFixed(2).replace('.', ',')]));const csv='\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bulla-${period}-${historySelect.value}.csv`;a.click();URL.revokeObjectURL(url)};
populateHistory();render();
