const D=window.AdminOrderData,select=document.querySelector('#daySelect'),demo=document.querySelector('#demoData'),search=document.querySelector('#employeeSearch');
const monday=D.mondayOf(new Date()),days=Array.from({length:5},(_,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);return date});
select.innerHTML=days.map(date=>`<option value="${D.localKey(date)}">${date.toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'2-digit'})}</option>`).join('');const today=D.localKey(new Date());if(days.some(d=>D.localKey(d)===today))select.value=today;
let expanded=new Set();function esc(value=''){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function allRows(){return[...D.rows(),...(demo.checked?D.demoRows(monday):[])]}
function filteredDayRows(){const query=search.value.trim().toLowerCase();return allRows().filter(row=>row.dateKey===select.value&&(!query||row.employeeName.toLowerCase().includes(query)||String(row.employeeNumber).toLowerCase().includes(query)))}
function groupMeals(rows){const map=new Map();rows.forEach(row=>{const key=`${row.mealName}|${row.category}`;if(!map.has(key))map.set(key,{key,name:row.mealName,category:row.category,rows:[]});map.get(key).rows.push(row)});return[...map.values()].sort((a,b)=>b.rows.reduce((n,r)=>n+r.quantity,0)-a.rows.reduce((n,r)=>n+r.quantity,0)||a.name.localeCompare(b.name))}
function render(){const rows=filteredDayRows(),meals=groupMeals(rows),employee=rows.filter(r=>r.type==='employee').reduce((n,r)=>n+r.quantity,0),guest=rows.filter(r=>r.type==='guest').reduce((n,r)=>n+r.quantity,0),date=D.parseDate(select.value);selectedDayHeading.textContent=date?.toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'2-digit'})||'Daily totals';totalLunches.textContent=employee+guest;employeeLunches.textContent=employee;guestLunches.textContent=guest;mealTypes.textContent=meals.length;mealSummary.innerHTML=meals.map(meal=>{const open=expanded.has(meal.key),total=meal.rows.reduce((n,r)=>n+r.quantity,0),people=meal.rows.filter(r=>r.type==='employee').sort(D.firstNameSort),guests=meal.rows.filter(r=>r.type==='guest').sort(D.firstNameSort);return `<article class="expandable-meal ${open?'open':''}" data-key="${esc(meal.key)}"><button class="summary-row meal-expand-button" type="button" aria-expanded="${open}"><span class="meal-expand-chevron">›</span><span class="summary-meal"><strong>${esc(meal.name)}</strong><span>${esc(meal.category)} · ${people.reduce((n,r)=>n+r.quantity,0)} employee${guests.length?` · ${guests.reduce((n,r)=>n+r.quantity,0)} guest`:''}</span></span><span class="portion-count">${total}</span></button><div class="meal-people" ${open?'':'hidden'}>${people.length?`<div class="people-section"><h3>Employees</h3>${people.map(r=>`<div class="person-order"><span>${esc(r.employeeName)} <small>${esc(r.employeeNumber)}</small></span><strong>${r.quantity}</strong></div>`).join('')}</div>`:''}${guests.length?`<div class="people-section guest"><h3>Guest lunches</h3>${guests.map(r=>`<div class="person-order"><span>${esc(r.employeeName)} <small>${esc(r.comment)}</small></span><strong>${r.quantity}</strong></div>`).join('')}</div>`:''}</div></article>`}).join('');emptyState.hidden=meals.length>0;const guestRows=rows.filter(r=>r.type==='guest').sort(D.firstNameSort);guestDetails.innerHTML=guestRows.length?guestRows.map(r=>`<div class="guest-row"><div><strong>${esc(r.comment||'No comment')}</strong><span>Ordered by ${esc(r.employeeName)} · ${esc(r.mealName)}</span></div><span class="guest-count">${r.quantity}</span></div>`).join(''):'<div class="empty-state"><strong>No guest orders</strong><span>No matching guest lunches for this day.</span></div>';dataNote.textContent=`Showing ${rows.length} order line${rows.length===1?'':'s'}${search.value.trim()?` matching “${search.value.trim()}”`:''}. Click a meal row to view names.`}
mealSummary.addEventListener('click',event=>{const button=event.target.closest('.meal-expand-button');if(!button)return;const key=button.closest('[data-key]').dataset.key;expanded.has(key)?expanded.delete(key):expanded.add(key);render()});select.addEventListener('change',()=>{expanded.clear();render()});demo.addEventListener('change',render);search.addEventListener('input',render);printButton.addEventListener('click',()=>window.print());render();
