const MENU_KEY='lunch-poc-menu-builder-v1',LIB_KEY='lunch-poc-meal-library-v1',OLD_KEYS=['lunch-poc-menu-config-v6','lunch-poc-menu-config-v5'],DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'],TYPES=['all','main','vegetarian','soup','other'];
const SAMPLE_LIBRARY=[
 ['meatballs','main','Meatballs with mashed potatoes','Köttbullar med potatismos','Lihapullat ja perunamuusi'],['salmon-sauce','main','Salmon in dill sauce with potatoes','Lax i dillsås med potatis','Lohi tillikastikkeessa ja perunat'],['macaroni-casserole','main','Macaroni casserole','Makaronilåda','Makaronilaatikko'],['chicken-curry','main','Chicken curry with rice','Kycklingcurry med ris','Kanacurry ja riisi'],['sausage-sauce','main','Sausage sauce with mashed potatoes','Korvsås med potatismos','Makkarakastike ja perunamuusi'],['oven-salmon','main','Oven-baked salmon with lemon potatoes','Ugnslax med citronpotatis','Uunilohi ja sitruunaperunat'],['karelian-stew','main','Karelian stew with potatoes','Karelsk stek med potatis','Karjalanpaisti ja perunat'],['minced-meat-sauce','main','Minced meat sauce with spaghetti','Köttfärssås med spaghetti','Jauhelihakastike ja spagetti'],['chicken-fillet','main','Chicken fillet with pepper sauce','Kycklingfilé med pepparsås','Broilerinfilee ja pippurikastike'],['fish-and-chips','main','Fish and chips with tartar sauce','Fish and chips med tartarsås','Fish and chips sekä tartarkastike'],['pulled-pork','main','Pulled pork with potato wedges','Pulled pork med klyftpotatis','Nyhtöpossu ja lohkoperunat'],['beef-stroganoff','main','Beef stroganoff with rice','Biff Stroganoff med ris','Naudanlihasuikaleet ja riisi'],['pork-cutlet','main','Pork cutlet with mushroom sauce','Fläskschnitzel med svampsås','Porsaanleike ja sienikastike'],['lasagne','main','Traditional lasagne','Traditionell lasagne','Perinteinen lasagne'],['pyttipanna','main','Pyttipanna with fried egg','Pyttipanna med stekt ägg','Pyttipannu ja paistettu kananmuna'],['chicken-pasta','main','Creamy chicken pasta','Krämig kycklingpasta','Kermainen kanapasta'],['reindeer','main','Sautéed reindeer with mashed potatoes and lingonberries','Renskav med potatismos och lingon','Poronkäristys, perunamuusi ja puolukat'],['duck','main','Duck breast with orange sauce and potato gratin','Ankbröst med apelsinsås och potatisgratäng','Ankanrintaa, appelsiinikastiketta ja perunagratiinia'],['wallenberg','main','Wallenberg steak with peas and browned butter','Wallenbergare med ärter och brynt smör','Wallenbergin pihvi, herneet ja ruskistettu voi'],['beef-bourguignon','main','Beef bourguignon with potato purée','Boeuf bourguignon med potatispuré','Boeuf bourguignon ja perunapyree'],
 ['veg-lasagne','vegetarian','Vegetable lasagne','Grönsakslasagne','Kasvislasagne'],['lentil-bolognese','vegetarian','Lentil bolognese with spaghetti','Linsbolognese med spaghetti','Linssibolognese ja spagetti'],['falafel','vegetarian','Falafel with couscous and yoghurt sauce','Falafel med couscous och yoghurtsås','Falafel, couscous ja jogurttikastike'],['spinach-pancakes','vegetarian','Spinach pancakes with lingonberries','Spenatplättar med lingon','Pinaattiletut ja puolukat'],['vegetable-curry','vegetarian','Vegetable curry with rice','Grönsakscurry med ris','Kasviscurry ja riisi'],['halloumi','vegetarian','Grilled halloumi with roasted vegetables','Grillad halloumi med rostade grönsaker','Grillattu halloumi ja paahdetut kasvikset'],['mushroom-risotto','vegetarian','Forest mushroom risotto','Skogssvamprisotto','Metsäsienirisotto'],['bean-chili','vegetarian','Bean chili with rice','Bönchili med ris','Papuchili ja riisi'],['goat-cheese-pasta','vegetarian','Goat cheese pasta with beetroot','Getostpasta med rödbeta','Vuohenjuustopasta ja punajuuri'],['cauliflower-steak','vegetarian','Roasted cauliflower steak with herb sauce','Rostad blomkålsstek med örtsås','Paahdettu kukkakaalipihvi ja yrttikastike'],
 ['salmon-soup','soup','Creamy salmon soup','Krämig laxsoppa','Kermainen lohikeitto'],['pea-soup','soup','Pea soup with mustard','Ärtsoppa med senap','Hernekeitto ja sinappi'],['tomato-soup','soup','Tomato soup','Tomatsoppa','Tomaattikeitto'],['minestrone','soup','Minestrone soup','Minestronesoppa','Minestronekeitto'],['mushroom-soup','soup','Creamy mushroom soup','Krämig svampsoppa','Kermainen sienikeitto'],['chicken-soup','soup','Chicken and noodle soup','Kyckling- och nudelsoppa','Kana-nuudelikeitto'],['root-veg-soup','soup','Roasted root vegetable soup','Soppa på rostade rotfrukter','Paahdettu juureskeitto'],['fish-soup','soup','Traditional fish soup','Traditionell fisksoppa','Perinteinen kalakeitto'],['asparagus-soup','soup','Asparagus soup','Sparrissoppa','Parsakeitto'],['pumpkin-soup','soup','Pumpkin soup with seeds','Pumpasoppa med frön','Kurpitsakeitto ja siemenet'],
 ['pancakes','other','Oven pancake with jam and whipped cream','Ugnspannkaka med sylt och vispgrädde','Pannukakku, hillo ja kermavaahto'],['berry-pie','other','Berry pie with vanilla sauce','Bärpaj med vaniljsås','Marjapiirakka ja vaniljakastike'],['creme-brulee','other','Crème brûlée','Crème brûlée','Crème brûlée'],['tiramisu','other','Tiramisu','Tiramisu','Tiramisu']
].map(x=>({id:x[0],type:x[1],names:{en:x[2],sv:x[3],fi:x[4]},active:true}));
const SAMPLE_WEEKS=[
 [['meatballs','veg-lasagne','salmon-soup'],['chicken-curry','lentil-bolognese','tomato-soup'],['salmon-sauce','spinach-pancakes','root-veg-soup'],['sausage-sauce','vegetable-curry','pea-soup','pancakes'],['fish-and-chips','falafel','mushroom-soup']],
 [['macaroni-casserole','halloumi','chicken-soup'],['beef-stroganoff','bean-chili','minestrone'],['oven-salmon','goat-cheese-pasta','tomato-soup'],['pork-cutlet','mushroom-risotto','fish-soup','berry-pie'],['lasagne','cauliflower-steak','pumpkin-soup']],
 [['minced-meat-sauce','lentil-bolognese','asparagus-soup'],['chicken-fillet','veg-lasagne','salmon-soup'],['karelian-stew','spinach-pancakes','mushroom-soup'],['duck','halloumi','root-veg-soup','creme-brulee'],['pyttipanna','vegetable-curry','pea-soup']],
 [['chicken-pasta','bean-chili','tomato-soup'],['pulled-pork','falafel','chicken-soup'],['reindeer','mushroom-risotto','fish-soup'],['wallenberg','goat-cheese-pasta','asparagus-soup','tiramisu'],['beef-bourguignon','cauliflower-steak','salmon-soup']]
];
let library=loadLibrary(),cfg=loadMenu(),active=0,filter='all',selected='',timer,dragSource=null;
const repeat=document.querySelector('#repeatWeeks'),tabs=document.querySelector('#weekTabs'),items=document.querySelector('#libraryItems'),search=document.querySelector('#librarySearch'),chips=document.querySelector('#categoryChips'),daysBox=document.querySelector('#dayEditors');repeat.value=cfg.repeatWeeks;
function t(x){return window.AdminI18n?.t(x)||x}function esc(x=''){return String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}function read(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function typeName(x){return{main:'Main dish',vegetarian:'Vegetarian',soup:'Soup',other:'Other'}[x]||'Other'}function name(m){const l=window.AdminI18n?.lang()||'sv';return m.names?.[l]||m.names?.sv||m.names?.en||m.names?.fi||'New dish'}function sampleMenu(){return{repeatWeeks:4,weeks:SAMPLE_WEEKS.map((week)=>({days:DAYS.map((day,i)=>({day,mealIds:[...week[i]]}))}))}}function blank(){return{days:DAYS.map(day=>({day,mealIds:[]}))}}
function loadLibrary(){const saved=read(LIB_KEY,[]);if(saved.length)return saved;localStorage.setItem(LIB_KEY,JSON.stringify(SAMPLE_LIBRARY));return structuredClone(SAMPLE_LIBRARY)}
function loadMenu(){const saved=read(MENU_KEY);if(saved?.weeks?.length)return saved;for(const key of OLD_KEYS){const old=read(key);if(old?.weeks?.length)return{repeatWeeks:+old.repeatWeeks||old.weeks.length,weeks:old.weeks.map(w=>({days:w.days.map(d=>({day:d.day,mealIds:d.meals.filter(m=>(m.names?.en||'').trim()).map(m=>library.find(x=>(x.names.en||'').toLowerCase()===(m.names.en||'').toLowerCase())?.id).filter(Boolean)}))}))}}return sampleMenu()}
function size(){const n=+repeat.value||4;while(cfg.weeks.length<n)cfg.weeks.push(blank());cfg.weeks.length=n;cfg.repeatWeeks=n;if(active>=n)active=n-1}
function renderTabs(){tabs.innerHTML=cfg.weeks.map((_,i)=>`<button class="week-tab ${i===active?'active':''}" data-week="${i}">${t('Week')} ${i+1}</button>`).join('');editingWeek.textContent=`${t('Week')} ${active+1}`;cycleTitle.textContent=`${cfg.repeatWeeks}-${t('week menu')}`}
function renderLibrary(){chips.innerHTML=TYPES.map(x=>`<button class="category-chip ${x===filter?'active':''}" data-type="${x}">${t(x==='all'?'All':typeName(x))}</button>`).join('');const q=search.value.trim().toLowerCase(),shown=library.filter(m=>m.active!==false&&(filter==='all'||m.type===filter)&&(!q||[...Object.values(m.names),typeName(m.type)].some(v=>String(v).toLowerCase().includes(q))));items.innerHTML=shown.map(m=>`<article class="library-dish ${selected===m.id?'selected':''}" draggable="true" tabindex="0" data-id="${esc(m.id)}"><div><span class="meal-category-badge ${m.type}">${t(typeName(m.type))}</span><strong>${esc(name(m))}</strong><small>${esc(m.names.en)}</small></div><span class="drag-handle">⋮⋮</span></article>`).join('')||`<div class="empty-state"><strong>${t('No matching dishes')}</strong></div>`}
function scheduled(mid,di,mi){const m=library.find(x=>x.id===mid);return m?`<div class="scheduled-dish" draggable="true" data-id="${mid}" data-day="${di}" data-index="${mi}"><span class="scheduled-grip">⋮⋮</span><div><strong>${esc(name(m))}</strong><small>${t(typeName(m.type))}</small></div><button class="remove-scheduled" data-remove="${di}:${mi}" aria-label="Remove">×</button></div>`:''}
function renderDays(){daysBox.innerHTML=cfg.weeks[active].days.map((d,di)=>`<article class="menu-builder-day"><header><div><strong>${t(d.day)}</strong><span>${d.mealIds.length} ${t(d.mealIds.length===1?'dish':'dishes')}</span></div><div class="day-actions"><button class="text-button" data-add="${di}" ${selected?'':'disabled'}>${t('Add')}</button><button class="text-button" data-clear="${di}" ${d.mealIds.length?'':'disabled'}>${t('Clear day')}</button></div></header><div class="day-drop-zone" data-drop-day="${di}">${d.mealIds.length?d.mealIds.map((mid,mi)=>scheduled(mid,di,mi)).join(''):`<div class="drop-placeholder"><strong>${t('Drop dishes here')}</strong><span>${t('or select a dish and press Add')}</span></div>`}</div></article>`).join('')}
function render(){size();renderTabs();renderLibrary();renderDays()}function add(day,mid,index){if(!mid||!library.some(x=>x.id===mid))return;const list=cfg.weeks[active].days[day].mealIds;list.splice(index==null?list.length:index,0,mid);renderDays()}function show(msg){toast.textContent=t(msg);toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2200)}function clearTargets(){document.querySelectorAll('.drag-over,.drop-before,.drop-after').forEach(x=>x.classList.remove('drag-over','drop-before','drop-after'))}
tabs.onclick=e=>{const b=e.target.closest('[data-week]');if(b){active=+b.dataset.week;selected='';render()}};repeat.onchange=render;search.oninput=renderLibrary;chips.onclick=e=>{const b=e.target.closest('[data-type]');if(b){filter=b.dataset.type;renderLibrary()}};items.onclick=e=>{const c=e.target.closest('[data-id]');if(c){selected=selected===c.dataset.id?'':c.dataset.id;renderLibrary();renderDays()}};items.ondragstart=e=>{const c=e.target.closest('[data-id]');if(c){dragSource=null;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('text/plain',c.dataset.id)}};
daysBox.addEventListener('dragstart',e=>{const r=e.target.closest('.scheduled-dish');if(!r)return;dragSource={day:+r.dataset.day,index:+r.dataset.index,id:r.dataset.id};e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',r.dataset.id);requestAnimationFrame(()=>r.classList.add('dragging'))});daysBox.addEventListener('dragend',()=>{dragSource=null;clearTargets();document.querySelectorAll('.dragging').forEach(x=>x.classList.remove('dragging'))});daysBox.addEventListener('dragover',e=>{const zone=e.target.closest('[data-drop-day]');if(!zone)return;e.preventDefault();clearTargets();const row=e.target.closest('.scheduled-dish');if(row){const box=row.getBoundingClientRect(),after=e.clientY>box.top+box.height/2;row.classList.add(after?'drop-after':'drop-before')}else zone.classList.add('drag-over')});daysBox.addEventListener('drop',e=>{const zone=e.target.closest('[data-drop-day]');if(!zone)return;e.preventDefault();const targetDay=+zone.dataset.dropDay,row=e.target.closest('.scheduled-dish');let targetIndex=row?+row.dataset.index+(row.classList.contains('drop-after')?1:0):cfg.weeks[active].days[targetDay].mealIds.length;let mid=e.dataTransfer.getData('text/plain');if(dragSource){const sourceList=cfg.weeks[active].days[dragSource.day].mealIds;[mid]=sourceList.splice(dragSource.index,1);if(dragSource.day===targetDay&&dragSource.index<targetIndex)targetIndex--}clearTargets();add(targetDay,mid,targetIndex)});
daysBox.onclick=e=>{const addB=e.target.closest('[data-add]');if(addB)return add(+addB.dataset.add,selected);const clear=e.target.closest('[data-clear]');if(clear){cfg.weeks[active].days[+clear.dataset.clear].mealIds=[];return renderDays()}const remove=e.target.closest('[data-remove]');if(remove){const[d,i]=remove.dataset.remove.split(':').map(Number);cfg.weeks[active].days[d].mealIds.splice(i,1);renderDays()}};
copyPrevious.onclick=()=>{if(!active)return show('Week 1 has no previous week');cfg.weeks[active]=structuredClone(cfg.weeks[active-1]);renderDays();show('Previous week copied')};loadExample.onclick=()=>{if(!confirm(t('Replace the current menu and library with the four-week example?')))return;library=structuredClone(SAMPLE_LIBRARY);cfg=sampleMenu();repeat.value=4;active=0;localStorage.setItem(LIB_KEY,JSON.stringify(library));localStorage.setItem(MENU_KEY,JSON.stringify(cfg));render();show('Example menu loaded')};saveMenu.onclick=()=>{size();localStorage.setItem(MENU_KEY,JSON.stringify(cfg));show('Menu saved')};document.addEventListener('admin-language-changed',render);render();
