window.AdminOrderData=(()=>{
const KEYS={menuBuilder:'lunch-poc-menu-builder-v1',mealLibrary:'lunch-poc-meal-library-v1',menu6:'lunch-poc-menu-config-v6',menu5:'lunch-poc-menu-config-v5',salads:'lunch-poc-salads-v5',employees:'lunch-poc-employees-v8',employee:'lunch-poc-orders-v2',guest:'lunch-poc-guest-orders-v2',guestComment:'lunch-poc-guest-task-v2',guestComments:'lunch-poc-guest-comments-v20',kiosk:'lunch-poc-kiosk-order-log-v8'};
const ANCHOR=new Date(2026,8,21);
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const defaultEmployees=[{employeeNumber:'10435',employeeName:'Jonas Westerlund'},{employeeNumber:'10473',employeeName:'Diana Fagerholm'},{employeeNumber:'10488',employeeName:'Thomas Nyström'},{employeeNumber:'10512',employeeName:'Anna Berg'},{employeeNumber:'10539',employeeName:'Mikael Laine'},{employeeNumber:'10604',employeeName:'Sofia Lind'}];
const fallbackMeals=[{type:'main',names:{en:'Meatballs with mashed potatoes'}},{type:'main2',names:{en:''}},{type:'vegetarian',names:{en:'Vegetable lasagne'}},{type:'soup',names:{en:'Tomato soup'}}];
const defaultSalads=[{en:'Vegetarian salad',active:true},{en:'Beef salad',active:true},{en:'Tuna salad',active:true},{en:'Pasta salad with chicken',active:true},{en:'Salmon salad',active:true},{en:'Chicken salad',active:true}];
const categories={main:'Main dish',main2:'Main dish',vegetarian:'Vegetarian',soup:'Soup',salad:'Salad'};
function json(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function localKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function parseDate(value){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!match)return null;return new Date(+match[1],+match[2]-1,+match[3])}
function mondayOf(date){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function employees(){const saved=json(KEYS.employees,null);return saved?.length?saved:defaultEmployees}
function employeeName(number,fallback='Unknown employee'){return employees().find(e=>String(e.employeeNumber)===String(number))?.employeeName||fallback}
function activeWeek(date){const cfg=json(KEYS.menu6,null)||json(KEYS.menu5,null);if(!cfg?.weeks?.length)return{days:weekdays.map(day=>({day,meals:structuredClone(fallbackMeals)}))};const cycle=Number(cfg.repeatWeeks)||cfg.weeks.length,week=Math.floor((mondayOf(date)-ANCHOR)/604800000),index=((week%cycle)+cycle)%cycle;return cfg.weeks[index]||cfg.weeks[0]}
function salads(){const saved=json(KEYS.salads,null);return(saved?.length?saved:defaultSalads).filter(s=>s.active!==false&&(s.en||'').trim())}
function mealsFor(date){const index=(date.getDay()+6)%7,builder=json(KEYS.menuBuilder,null),library=json(KEYS.mealLibrary,[]),language=localStorage.getItem('lunch-poc-language-v1')||localStorage.getItem('lunch-poc-admin-language-v1')||'en';let dishes;if(builder?.weeks?.length){const cycle=Number(builder.repeatWeeks)||builder.weeks.length,week=Math.floor((mondayOf(date)-ANCHOR)/604800000),wi=((week%cycle)+cycle)%cycle,ids=builder.weeks[wi]?.days?.[index]?.mealIds||[];dishes=ids.map(id=>library.find(m=>m.id===id)).filter(Boolean).map(m=>({name:(m.names?.[language]||m.names?.en||m.names?.sv||m.names?.fi||'').trim(),category:categories[m.type]||'Meal'})).filter(m=>m.name)}else{const configured=activeWeek(date)?.days?.[index]?.meals||fallbackMeals;dishes=configured.filter(m=>(m.names?.en||'').trim()).map(m=>({name:(m.names?.[language]||m.names?.en||'').trim(),category:categories[m.type]||'Meal'}))}return[...dishes,...salads().map(s=>({name:(s[language]||s.en).trim(),category:'Salad'}))]}
function parseSelection(selectionKey,quantity){const split=String(selectionKey||'').lastIndexOf(':'),dateKey=String(selectionKey||'').slice(0,split),mealIndex=Number(String(selectionKey||'').slice(split+1)),date=parseDate(dateKey),count=Number(quantity)||0;if(split<0||!date||!Number.isInteger(mealIndex)||mealIndex<0||!count)return null;const meal=mealsFor(date)[mealIndex];return{dateKey,mealIndex,mealName:meal?.name||'Unknown menu item',category:meal?.category||'Meal',quantity:count}}
function browserRows(){const rows=[];Object.keys(localStorage).filter(k=>k===KEYS.employee||k.startsWith(KEYS.employee+':')).forEach(key=>{const number=key.split(':')[1]||'10435',name=employeeName(number,number==='10435'?'Jonas Westerlund':`Employee ${number}`);Object.entries(json(key,{})).forEach(([selectionKey,quantity])=>{const item=parseSelection(selectionKey,quantity);if(item)rows.push({...item,type:'employee',employeeNumber:number,employeeName:name,comment:'',source:'browser'})})});Object.keys(localStorage).filter(k=>k===KEYS.guest||k.startsWith(KEYS.guest+':')).forEach(key=>{const number=key.split(':')[1]||'10435',name=employeeName(number,number==='10435'?'Jonas Westerlund':`Employee ${number}`),comment=localStorage.getItem(KEYS.guestComment+(key.includes(':')?':'+number:''))||'',comments=json(KEYS.guestComments+(key.includes(':')?':'+number:''),{});Object.entries(json(key,{})).forEach(([selectionKey,quantity])=>{const item=parseSelection(selectionKey,quantity);if(item)rows.push({...item,type:'guest',employeeNumber:number,employeeName:name,comment:Object.prototype.hasOwnProperty.call(comments,selectionKey)?comments[selectionKey]:comment,source:'browser'})})});return rows}
function kioskRows(){const seen=new Set(),rows=[];for(const record of json(KEYS.kiosk,[])){if(!record||!['employee','guest'].includes(record.type))continue;const id=String(record.id||`${record.timestamp||''}|${record.type}|${record.employeeNumber}|${record.selectionKey}|${record.quantity}|${record.comment||''}`);if(seen.has(id))continue;seen.add(id);const item=parseSelection(record.selectionKey,record.quantity);if(item)rows.push({...item,type:record.type,employeeNumber:String(record.employeeNumber||''),employeeName:record.employeeName||employeeName(record.employeeNumber),comment:record.type==='guest'?String(record.comment||''):'',source:'kiosk'})}return rows}
function rows(){return[...browserRows(),...kioskRows()]}
function demoRows(monday){const names=['Anna Berg','Diana Fagerholm','Jonas Westerlund','Mikael Laine','Sofia Lind','Thomas Nyström'];const out=[];for(let day=0;day<5;day++){const date=new Date(monday);date.setDate(monday.getDate()+day);const menu=mealsFor(date);names.forEach((name,i)=>{const meal=menu[(i+day)%Math.max(1,Math.min(menu.length,6))];out.push({dateKey:localKey(date),mealIndex:(i+day)%6,mealName:meal?.name||'Lunch',category:meal?.category||'Meal',quantity:i===0&&day===1?2:1,type:'employee',employeeNumber:`D${i+1}`,employeeName:name,comment:'',source:'demo'})});if(menu[1])out.push({dateKey:localKey(date),mealIndex:1,mealName:menu[1].name,category:menu[1].category,quantity:2,type:'guest',employeeNumber:'D1',employeeName:'Anna Berg',comment:day%2?'Supplier visit':'Project 2471',source:'demo'})}return out}
function firstNameSort(a,b){const af=String(a.employeeName).trim().split(/\s+/)[0],bf=String(b.employeeName).trim().split(/\s+/)[0];return af.localeCompare(bf)||a.employeeName.localeCompare(b.employeeName)}
return{KEYS,json,localKey,parseDate,mondayOf,employees,employeeName,mealsFor,rows,demoRows,firstNameSort};
})();
