const employeeKey='lunch-poc-employees-v8',userKey='lunch-poc-current-user-v17',languageKey='lunch-poc-language-v5';
const defaults=[{cardNumber:'123',employeeNumber:'10435',employeeName:'Jonas Westerlund'},{cardNumber:'456',employeeNumber:'10473',employeeName:'Diana Fagerholm'},{cardNumber:'789',employeeNumber:'10488',employeeName:'Thomas Nyström'},{cardNumber:'221',employeeNumber:'10512',employeeName:'Anna Berg'},{cardNumber:'314',employeeNumber:'10539',employeeName:'Mikael Laine'},{cardNumber:'808',employeeNumber:'10604',employeeName:'Sofia Lind'}];
const text={en:{title:'Lunch service',intro:'Enter your employee number to continue.',number:'Employee number',button:'Continue',unknown:'Employee number not recognized.',language:'Language',note:'POC: the login is remembered on this device until you log out or clear browser data.'},sv:{title:'Lunchtjänst',intro:'Ange ditt anställningsnummer för att fortsätta.',number:'Anställningsnummer',button:'Fortsätt',unknown:'Anställningsnumret känns inte igen.',language:'Språk',note:'POC: inloggningen sparas på den här enheten tills du loggar ut eller rensar webbläsardata.'},fi:{title:'Lounaspalvelu',intro:'Jatka syöttämällä työntekijänumerosi.',number:'Työntekijänumero',button:'Jatka',unknown:'Työntekijänumeroa ei löytynyt.',language:'Kieli',note:'POC: kirjautuminen säilyy tällä laitteella, kunnes kirjaudut ulos tai tyhjennät selaintiedot.'}};
function employees(){try{const saved=JSON.parse(localStorage.getItem(employeeKey));if(saved?.length)return saved}catch{}localStorage.setItem(employeeKey,JSON.stringify(defaults));return defaults}
function currentUser(){try{return JSON.parse(localStorage.getItem(userKey))}catch{return null}}
if(currentUser()?.employeeNumber)location.replace('index.html');
const form=document.querySelector('#loginForm'),input=document.querySelector('#employeeNumber'),message=document.querySelector('#loginMessage'),select=document.querySelector('#loginLanguage');let language=localStorage.getItem(languageKey)||'en';
function render(){const t=text[language];document.documentElement.lang=language;document.title=t.title;loginTitle.textContent=t.title;loginIntro.textContent=t.intro;employeeNumberLabel.textContent=t.number;loginButton.textContent=t.button;document.querySelector('label[for="loginLanguage"]').textContent=t.language;pocNote.textContent=t.note;select.value=language}
select.addEventListener('change',()=>{language=select.value;localStorage.setItem(languageKey,language);message.textContent='';render()});
form.addEventListener('submit',event=>{event.preventDefault();const employee=employees().find(item=>String(item.employeeNumber).trim()===input.value.trim());if(!employee){message.textContent=text[language].unknown;message.className='login-message error';input.select();return}localStorage.setItem(userKey,JSON.stringify({employeeNumber:String(employee.employeeNumber),employeeName:employee.employeeName,cardNumber:String(employee.cardNumber||'')}));location.replace('index.html')});render();
