const KEYS={language:'lunch-poc-language-v5',menuBuilder:'lunch-poc-menu-builder-v1',mealLibrary:'lunch-poc-meal-library-v1',menu6:'lunch-poc-menu-config-v6',menu5:'lunch-poc-menu-config-v5',salads:'lunch-poc-salads-v5',employee:'lunch-poc-orders-v2',guest:'lunch-poc-guest-orders-v2',guestComment:'lunch-poc-guest-task-v2',guestComments:'lunch-poc-guest-comments-v20',kiosk:'lunch-poc-kiosk-order-log-v8'};
const userKey='lunch-poc-current-user-v17';let currentUser;try{currentUser=JSON.parse(localStorage.getItem(userKey))}catch{}if(!currentUser?.employeeNumber)location.replace('login.html');
const ANCHOR_MONDAY=new Date(2026,8,21);
let language=localStorage.getItem(KEYS.language)||'en';
const copy={
 en:{title:'My orders',week:'This week',overview:'Lunch overview',intro:'Check your personal and guest lunch orders for each weekday.',summary:'Summary',personalWeek:'Personal lunches this week',guestWeek:'Guest lunches this week',month:'Total lunches this month',personal:'Personal',guest:'Guest',none:'No order',project:'Work task / project',menu:'Lunch menu',source:'Shows the current employee’s browser and kiosk orders stored in this browser.',back:'Back to lunch ordering'},
 sv:{title:'Mina beställningar',week:'Den här veckan',overview:'Lunchöversikt',intro:'Kontrollera dina egna lunchbeställningar och gästluncher för varje vardag.',summary:'Sammanfattning',personalWeek:'Egna luncher den här veckan',guestWeek:'Gästluncher den här veckan',month:'Totalt antal luncher den här månaden',personal:'Egna luncher',guest:'Gästluncher',none:'Ingen beställning',project:'Arbetsuppgift / projekt',menu:'Lunchmeny',source:'Visar den aktuella användarens webbläsar- och kioskbeställningar som sparats i den här webbläsaren.',back:'Tillbaka till lunchbeställning'},
 fi:{title:'Omat tilaukset',week:'Tämä viikko',overview:'Lounasyhteenveto',intro:'Tarkista omat lounastilauksesi ja vieraslounaat jokaiselle arkipäivälle.',summary:'Yhteenveto',personalWeek:'Omat lounaat tällä viikolla',guestWeek:'Vieraslounaat tällä viikolla',month:'Lounaita yhteensä tässä kuussa',personal:'Omat lounaat',guest:'Vieraslounaat',none:'Ei tilausta',project:'Työtehtävä / projekti',menu:'Lounaslista',source:'Näyttää nykyisen käyttäjän tähän selaimeen tallennetut selain- ja kioskitilaukset.',back:'Takaisin lounastilaukseen'}
};
const weekdays=[{en:'Monday',sv:'Måndag',fi:'Maanantai'},{en:'Tuesday',sv:'Tisdag',fi:'Tiistai'},{en:'Wednesday',sv:'Onsdag',fi:'Keskiviikko'},{en:'Thursday',sv:'Torsdag',fi:'Torstai'},{en:'Friday',sv:'Fredag',fi:'Perjantai'}];
const categories={main:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},main2:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},vegetarian:{en:'Vegetarian',sv:'Vegetarisk',fi:'Kasvisruoka'},soup:{en:'Soup',sv:'Soppa',fi:'Keitto'},salad:{en:'Salad',sv:'Sallad',fi:'Salaatti'},other:{en:'Other',sv:'Övrigt',fi:'Muu'}};
const fallbackMeals=[{type:'main',names:{en:'Meatballs with mashed potatoes',sv:'Köttbullar med potatismos',fi:'Lihapullat ja perunamuusi'}},{type:'main2',names:{en:'',sv:'',fi:''}},{type:'vegetarian',names:{en:'Vegetable lasagne',sv:'Grönsakslasagne',fi:'Kasvislasagne'}},{type:'soup',names:{en:'Tomato soup',sv:'Tomatsoppa',fi:'Tomaattikeitto'}}];
const defaultSalads=[{en:'Vegetarian salad',sv:'Vegetarisk sallad',fi:'Kasvissalaatti',active:true},{en:'Beef salad',sv:'Nötköttssallad',fi:'Naudanlihasalaatti',active:true},{en:'Tuna salad',sv:'Tonfisksallad',fi:'Tonnikalasalaatti',active:true},{en:'Pasta salad with chicken',sv:'Pastasallad med kyckling',fi:'Pastasalaatti kanalla',active:true},{en:'Salmon salad',sv:'Laxsallad',fi:'Lohisalaatti',active:true},{en:'Chicken salad',sv:'Kycklingsallad',fi:'Kanasalaatti',active:true}];
function readJson(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function parseDate(value){const parts=String(value).split('-').map(Number);if(parts.length!==3||parts.some(Number.isNaN))return null;const date=new Date(parts[0],parts[1]-1,parts[2]);return dateKey(date)===value?date:null}
function mondayOf(date){const result=new Date(date);result.setHours(0,0,0,0);result.setDate(result.getDate()-((result.getDay()+6)%7));return result}
function menuWeek(date){
 const builder=readJson(KEYS.menuBuilder,null),library=readJson(KEYS.mealLibrary,[]);
 if(builder?.weeks?.length){const cycle=Number(builder.repeatWeeks)||builder.weeks.length,weekNumber=Math.floor((mondayOf(date)-ANCHOR_MONDAY)/604800000),index=((weekNumber%cycle)+cycle)%cycle,week=builder.weeks[index]||builder.weeks[0];return{days:weekdays.map((day,i)=>({day:day.en,meals:(week.days?.[i]?.mealIds||[]).map(id=>library.find(m=>m.id===id)).filter(Boolean).map(m=>({type:m.type,names:m.names}))}))}}
 const config=readJson(KEYS.menu6,null)||readJson(KEYS.menu5,null);if(!config?.weeks?.length)return{days:weekdays.map(day=>({day:day.en,meals:structuredClone(fallbackMeals)}))};const cycle=Number(config.repeatWeeks)||config.weeks.length,weekNumber=Math.floor((mondayOf(date)-ANCHOR_MONDAY)/604800000),index=((weekNumber%cycle)+cycle)%cycle;return config.weeks[index]||config.weeks[0]
}
function activeSalads(){const saved=readJson(KEYS.salads,null);return(saved?.length?saved:defaultSalads).filter(item=>item.active!==false)}
function translatedName(names){return String(names?.[language]||names?.en||'').trim()}
function mealsFor(date){const dayIndex=(date.getDay()+6)%7;const configured=menuWeek(date)?.days?.[dayIndex]?.meals||fallbackMeals;const meals=configured.filter(meal=>translatedName(meal.names)).map(meal=>({name:translatedName(meal.names),category:categories[meal.type]?.[language]||categories[meal.type]?.en||''}));const salads=activeSalads().filter(salad=>translatedName(salad)).map(salad=>({name:translatedName(salad),category:categories.salad[language]}));return[...meals,...salads]}
function orderFromSelection(selectionKey,quantity,type,comment,unique){const separator=String(selectionKey).lastIndexOf(':'),key=String(selectionKey).slice(0,separator),mealIndex=Number(String(selectionKey).slice(separator+1)),date=parseDate(key),count=Number(quantity)||0;if(separator<0||!date||!Number.isInteger(mealIndex)||mealIndex<0||!count)return null;const meal=mealsFor(date)[mealIndex];return{unique,dateKey:key,type,quantity:count,mealName:meal?.name||copy[language].menu,category:meal?.category||'',comment:type==='guest'?String(comment||''):''}}
function browserOrders(){const comment=localStorage.getItem(KEYS.guestComment+':'+currentUser.employeeNumber)||'',comments=readJson(KEYS.guestComments+':'+currentUser.employeeNumber,{});const result=[];for(const [selectionKey,quantity] of Object.entries(readJson(KEYS.employee+':'+currentUser.employeeNumber,{}))){const row=orderFromSelection(selectionKey,quantity,'employee','',`browser:employee:${selectionKey}`);if(row)result.push(row)}for(const [selectionKey,quantity] of Object.entries(readJson(KEYS.guest+':'+currentUser.employeeNumber,{}))){const row=orderFromSelection(selectionKey,quantity,'guest',Object.prototype.hasOwnProperty.call(comments,selectionKey)?comments[selectionKey]:comment,`browser:guest:${selectionKey}`);if(row)result.push(row)}return result}
function kioskOrders(){const result=[],seen=new Set();for(const row of readJson(KEYS.kiosk,[])){if(!row||String(row.employeeNumber)!==String(currentUser.employeeNumber)||!['employee','guest'].includes(row.type))continue;const identity=String(row.id||`${row.timestamp||''}|${row.type}|${row.selectionKey}|${row.quantity}|${row.comment||''}`);if(seen.has(identity))continue;seen.add(identity);const order=orderFromSelection(row.selectionKey,row.quantity,row.type,row.comment,`kiosk:${identity}`);if(order)result.push(order)}return result}
function allOrders(){return[...browserOrders(),...kioskOrders()]}
function escapeHtml(value=''){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function formatDate(date){return `${String(date.getDate()).padStart(2,'0')}.${String(date.getMonth()+1).padStart(2,'0')}`}
function orderGroup(label,orders,isGuest){if(!orders.length)return'';return `<div class="my-order-group ${isGuest?'guest':''}"><h3>${escapeHtml(label)}</h3>${orders.map(order=>`<div class="my-order-line"><div><strong>${escapeHtml(order.mealName)}</strong><span>${escapeHtml(order.category)}${isGuest&&order.comment?` · ${escapeHtml(copy[language].project)}: ${escapeHtml(order.comment)}`:''}</span></div><b>× ${order.quantity}</b></div>`).join('')}</div>`}
function applyLabels(){const t=copy[language];document.documentElement.lang=language;document.title=t.title;pageTitle.textContent=t.title;pageSubtitle.textContent=t.week;introEyebrow.textContent=t.overview;weekHeading.textContent=t.week;introText.textContent=t.intro;summaryHeading.textContent=t.summary;personalLabel.textContent=t.personalWeek;guestLabel.textContent=t.guestWeek;monthLabel.textContent=t.month;sourceNote.textContent=t.source;backButton.setAttribute('aria-label',t.back)}
function render(){applyLabels();const orders=allOrders(),monday=mondayOf(new Date()),dates=Array.from({length:5},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return date});ordersList.innerHTML=dates.map((date,index)=>{const key=dateKey(date),personal=orders.filter(order=>order.dateKey===key&&order.type==='employee'),guests=orders.filter(order=>order.dateKey===key&&order.type==='guest'),count=[...personal,...guests].reduce((sum,order)=>sum+order.quantity,0);return `<article class="my-order-day"><div class="my-order-day-head"><div><strong>${escapeHtml(weekdays[index][language])} ${formatDate(date)}</strong><span>${count?escapeHtml(copy[language].menu):escapeHtml(copy[language].none)}</span></div><span class="day-total ${count?'has-orders':''}">🍴 ${count}</span></div>${count?`<div class="my-order-details">${orderGroup(copy[language].personal,personal,false)}${orderGroup(copy[language].guest,guests,true)}</div>`:`<div class="my-order-empty">${escapeHtml(copy[language].none)}</div>`}</article>`}).join('');const friday=new Date(monday);friday.setDate(monday.getDate()+4);const inWeek=order=>{const date=parseDate(order.dateKey);return date&&date>=monday&&date<=friday};const now=new Date(),inMonth=order=>{const date=parseDate(order.dateKey);return date&&date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()};personalTotal.textContent=orders.filter(order=>order.type==='employee'&&inWeek(order)).reduce((sum,order)=>sum+order.quantity,0);guestTotal.textContent=orders.filter(order=>order.type==='guest'&&inWeek(order)).reduce((sum,order)=>sum+order.quantity,0);monthTotal.textContent=orders.filter(inMonth).reduce((sum,order)=>sum+order.quantity,0)}
currentUserName.textContent=currentUser.employeeName;logoutButton.addEventListener('click',()=>{localStorage.removeItem(userKey);location.replace('login.html')});const languageSelect=document.querySelector('#languageSelect');languageSelect.value=language;languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(KEYS.language,language);render()});render();
